### ISSUE TITLE
Documentation for Posted Notifications

### ISSUE THREAD

**Issue by richardpineo** [PredixDev/PredixMobileSDK#6]
https://github.com/PredixDev/PredixMobileSDK/wiki/Posted-Notifications

I'm unclear what these notifications represent. Can you provide more documentation as to what the connectivity states mean?  

For example, I would expect any notification to include either 'Online' or 'Offline' but this isn't the case.

Reproduction Path A: Start offline, switch to online, switch to offline
Initial state:  ["OfflineAuthenticated"]
After online: ["Online", "Wifi", "OfflineAuthenticated"]
After offline: ["OfflineAuthenticated"]

Reproduction Path B:  Start online, switch to offline, switch to online
Initial state:  ["Online", "Wifi", "Authenticated"]
After offline: ["Offline"]
After online: ["Online","Wifi","Authenticated"]

**Comment by richardpineo** [comment]
For example, a simple check for whether my application is offline or online might be something like:
const stateIsOffline = x => x === 'Offline' || x === 'OfflineAuthenticated';
const offline = _.find(states, stateIsOffline) ? true : false;

But this doesn't work because the OfflineAuthenticated state applies to both offline and online mode. Is the correct thing to do here is check the presence of the state 'Online'?

**Comment by andyjohns** [comment]
See the description in the Connectivity Service documentation: [https://github.com/PredixDev/PredixMobileSDK/wiki/Connectivity](https://github.com/PredixDev/PredixMobileSDK/wiki/Connectivity)

**Comment by richardpineo** [comment]
Thanks for the response, Andy. My feeling is that there is a bug in the states reported when shifting to offline mode when offline authenticated. I say this because of the statement in the connectivity document:

> If a device is offline, and the device reports that no network connection is available, the response data will include: ["Offline"]

In the meantime, can you suggest a good way to detect this? My working theory is to check for the presence of the state 'Online' to determine whether the device is online but it's confusing because of the 'Internet' state.

**Comment by andyjohns** [comment]
The Connectivity service is used to detect the current connectivity status. You can subscribe to events 
from this service to be actively alerted to changes by using the Notify service to subscribe to the ReachabilityWatcherNotification event.

The connectivity states of Authenticated and OfflineAuthenticated are independent of physical device states, Offline, Internet and Online. So it's perfectly valid to be both Authenticated and OfflineAuthenticated or neither. 

OfflineAuthenticated means the user successfully completely the Offline authentication process.

Authenticated means the user successfully logged in online, and the user's session is currently still active.

Offline indicates the device physically has no network connection, no IP address, no service, nothing.

Internet indicates the device does have an internet connection, but cannot reach the configured PredixSync service. This could be due to a misconfiguration, the service being down, a proxy error, network error, etc.

Online indicates the device can successfully reach it's configured PredixSync service. Note that the Authenticated state can only occur when the device is also Online, because the Authenticated state requires a connection to PredixSync for authentication validation.

**Comment by richardpineo** [comment]
After a bit of back-and-forth (thanks @andyjohns!) we came up with the following check in the callback to ReachabilityWatcherNotification to determine whether the application is 'offline':
`const offline = !states.includes('Online');
`
where states is the array passed in the notification callback.
